server:
  port: 8090

spring:
  application:
    name: blog-provider
  datasource:
    url: jdbc:mysql://localhost:3306/indiv_blog?serverTimezone=UTC&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

dubbo:
  application:
    name: blog-provider
  protocol:
    name: dubbo
    port: 20880
  registry:
    address: zookeeper://localhost:2181
    timeout: 5000
  consumer:
    timeout: 5000


demo:
  service:
    version: 1.0.0


# mybatis的相关配置
mybatis-plus:
  # 映射文件位置
  mapper-locations: classpath*:com/conf/mybatis/mappings/*.xml
  global-config:
      #主键类型  0:"数据库ID自增", 1:"用户输入ID",2:"全局唯一ID (数字类型唯一ID)", 3:"全局唯一ID UUID";
      id-type: 0
  # 输出SQL执行语句
  configuration:
    logImpl: org.apache.ibatis.logging.stdout.StdOutImpl










